### ISSUE TITLE
Open search results in a background tab

### ISSUE THREAD

**Issue by richardneish** [dillbyrne/Search-On#1]
Love this plugin!  Thanks for the good work.

It would be great to be able to open search results in a background tab.  For the built-in context search this is controlled with the setting "browser.search.context.loadInBackground", and it would be ideal if this add-on used the same setting.

I thin kthis is the same feature that is requested in this review: https://addons.mozilla.org/en-GB/firefox/addon/search-on/reviews/730724/ "option to open Tab hidden"

**Comment by dillbyrne** [comment]
Hi @richardneish . I have updated the addon and it will now honour that preference. It may take a few days for the addon to be reviewed on AMO.
